### ISSUE TITLE
求教

### ISSUE THREAD

**Issue by Ryuurock** [kongchenglc/Demo#2]
https://github.com/kongchenglc/Demo/blob/a2fc5213b651b84cfe5d49d8156ad54f55956b23/particle/index.html#L204

大佬好，这一块的代码不是特别懂，是为了做什么宽高限制的算法吗，或者这种计算有什么用处，
我知道dot.iz是随机了一个一个负数到正数的区间

*****
似乎是动画速度控制？

**Comment by kongchenglc** [comment]
@Ryuurock 这个是为了得到一个系数scale，这个系数会影响绘制的点的明暗程度和大小、以及偏移速度（而这几点结合起来可以产生纵坐标上的视觉差）。这个计算的公式不是确定的，可以自己确定，我只是找了个觉得合适的计算方法。  
https://github.com/kongchenglc/Demo/blob/a2fc5213b651b84cfe5d49d8156ad54f55956b23/particle/index.html#L208

**Comment by Ryuurock** [comment]
好的 谢谢解答
